/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package turismogrupo77.vistas;

import javax.swing.JOptionPane;
import turismogrupo77.accesoADatos.CiudadData;
import turismogrupo77.entidades.Ciudad;
import turismogrupo77.entidades.Pasaje;
import turismogrupo77.accesoADatos.PasajeData;

/**
 *
 * @author Decker Soluciones
 */
public class FormularioPasaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioPasaje
     */
    public FormularioPasaje() {
        initComponents();
    }

    private void borrarFormulario() {
        jTOrigen.setText("");
        jTOrigen.setEnabled(true);
        jTDestino.setEnabled(true);
        jTDestino.setText("");
        jTProvinciaOrigen.setText("");
        jTProvinciaDestino.setText("");
        jTIDciudadOrigen.setText("");
        jTIDciudadDestino.setText("");

        jBBuscarOrigen.setEnabled(true);
        jBBuscarDestino.setEnabled(true);
        jBGuardar.setEnabled(false);
        jTIDpasaje.setText("");

        jREstado.setSelected(false);
        jREstado.setEnabled(false);

        jCTransporte.setEnabled(false);
        jTImporte.setText(null);
        jTImporte.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTIDpasaje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTDestino = new javax.swing.JTextField();
        jBBuscarDestino = new javax.swing.JButton();
        jTProvinciaDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCTransporte = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTOrigen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTProvinciaOrigen = new javax.swing.JTextField();
        jBBuscarOrigen = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jREstado = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTImporte = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTIDciudadOrigen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTIDciudadDestino = new javax.swing.JTextField();
        jBSalir = new javax.swing.JButton();

        jLabel1.setText("Gestion de Pasajes");

        jLabel2.setText("Identificador");

        jTIDpasaje.setEnabled(false);

        jLabel3.setText("Destino");

        jBBuscarDestino.setText("Buscar");
        jBBuscarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarDestinoActionPerformed(evt);
            }
        });

        jTProvinciaDestino.setEnabled(false);

        jLabel4.setText("Provincia");

        jCTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colectivo", "Tren", "Barco", "Avion" }));
        jCTransporte.setEnabled(false);

        jLabel5.setText("Tipo Transporte");

        jLabel6.setText("Origen");

        jLabel7.setText("Provincia");

        jTProvinciaOrigen.setEnabled(false);

        jBBuscarOrigen.setText("Buscar");
        jBBuscarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarOrigenActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jREstado.setText("Disponible");
        jREstado.setEnabled(false);

        jLabel8.setText("Importe en $:");

        jTImporte.setEnabled(false);

        jBGuardar.setText("Guardar Cambios");
        jBGuardar.setEnabled(false);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel9.setText("ID");

        jTIDciudadOrigen.setEnabled(false);

        jLabel10.setText("ID");

        jTIDciudadDestino.setEnabled(false);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBCancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBGuardar))
                            .addComponent(jCTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSalir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTIDciudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBBuscarOrigen)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTIDpasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jREstado)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 25, Short.MAX_VALUE)
                                .addComponent(jBBuscarDestino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTIDciudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTIDpasaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jREstado))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarDestino)
                    .addComponent(jLabel6)
                    .addComponent(jTOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarOrigen))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jTIDciudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTIDciudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuardar))
                .addGap(18, 18, 18)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarOrigenActionPerformed
        // TODO add your handling code here:
        Ciudad ciudadencontrada = new Ciudad();
        CiudadData city = new CiudadData();

        ciudadencontrada = city.buscarCiudad(jTOrigen.getText());

        if (ciudadencontrada != null) {
            jTOrigen.setText(ciudadencontrada.getNombre());
            jTProvinciaOrigen.setText(ciudadencontrada.getProvincia());
            jTIDciudadOrigen.setText(ciudadencontrada.getIdCiudad() + "");

            //JOptionPane.showMessageDialog(null,"Ciudad Origen Encontrada");
            jTOrigen.setEnabled(false);
            jTProvinciaOrigen.setEnabled(false);
            jTImporte.setEnabled(true);
            jCTransporte.setEnabled(true);
            jCTransporte.setSelectedIndex(0);
            jBGuardar.setEnabled(true);
            jBCancelar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "La ciudad no Existe");
        }

    }//GEN-LAST:event_jBBuscarOrigenActionPerformed

    private void jBBuscarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarDestinoActionPerformed
        // TODO add your handling code here:
        Ciudad ciudadencontrada = new Ciudad();
        CiudadData city = new CiudadData();

        ciudadencontrada = city.buscarCiudad(jTDestino.getText());

        if (ciudadencontrada != null) {
            jTDestino.setText(ciudadencontrada.getNombre());
            jTProvinciaDestino.setText(ciudadencontrada.getProvincia());
            jTIDciudadDestino.setText(ciudadencontrada.getIdCiudad() + "");

            //JOptionPane.showMessageDialog(null,"Ciudad Destino Encontrada");
            jTDestino.setEnabled(false);
            jTProvinciaDestino.setEnabled(false);
            jTImporte.setEnabled(true);
            jCTransporte.setEnabled(true);
            jREstado.setEnabled(true);
            jCTransporte.setSelectedIndex(0);
            jBGuardar.setEnabled(true);
            jBCancelar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "La ciudad no Existe");
        }
    }//GEN-LAST:event_jBBuscarDestinoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        Pasaje pass = new Pasaje();
        CiudadData city = new CiudadData();
        int repetido = 0;
        Pasaje origen = new Pasaje();
        Pasaje destino = new Pasaje();
        PasajeData passData = new PasajeData();

        if (jTIDciudadOrigen.getText().equals("") || jTIDciudadDestino.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Origen y un Destino");
            return;
        }

        repetido = passData.buscarPasajeRepetido(Integer.parseInt(jTIDciudadOrigen.getText()), Integer.parseInt(jTIDciudadDestino.getText()), jCTransporte.getSelectedItem()+"");
        
        if (repetido != 0) {
            pass = passData.buscarPasaje(repetido);
            pass.setImporte(Double.valueOf(jTImporte.getText()));
            pass.setEstado(jREstado.isSelected());
            pass.setTipoTransporte(jCTransporte.getSelectedItem()+"");
            passData.modificarPasaje(pass);
            jTIDpasaje.setText(pass.getIdPasaje()+"");
            return;
        }

        Ciudad ciudadOrigen = city.buscarCiudad(jTOrigen.getText());
        Ciudad ciudadDest = city.buscarCiudad(jTDestino.getText());
        pass = new Pasaje(jCTransporte.getSelectedItem() + "", Double.valueOf(jTImporte.getText()), ciudadOrigen, ciudadDest, jREstado.isSelected());
        jTIDpasaje.setText(passData.guardarPasaje(pass)+"");
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        borrarFormulario();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarDestino;
    private javax.swing.JButton jBBuscarOrigen;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jREstado;
    private javax.swing.JTextField jTDestino;
    private javax.swing.JTextField jTIDciudadDestino;
    private javax.swing.JTextField jTIDciudadOrigen;
    private javax.swing.JTextField jTIDpasaje;
    private javax.swing.JTextField jTImporte;
    private javax.swing.JTextField jTOrigen;
    private javax.swing.JTextField jTProvinciaDestino;
    private javax.swing.JTextField jTProvinciaOrigen;
    // End of variables declaration//GEN-END:variables
}
