/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package turismogrupo77.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import turismogrupo77.accesoADatos.AlojamientoData;
import turismogrupo77.accesoADatos.CiudadData;
import turismogrupo77.accesoADatos.PaqueteData;
import turismogrupo77.accesoADatos.PasajeData;
import turismogrupo77.entidades.Alojamiento;
import turismogrupo77.entidades.Ciudad;
import turismogrupo77.entidades.Paquete;
import turismogrupo77.entidades.Pasaje;

/**
 *
 * @author Decker Soluciones by Fernando Oliva
 */
public class VistaPaquetes extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloAlojamiento;
    private DefaultTableModel modeloPasaje;

    public VistaPaquetes() {
        initComponents();
        modeloAlojamiento = new DefaultTableModel();
        modeloPasaje = new DefaultTableModel();
        armarCabeceraTablaAlojamiento();
        armarCabeceraTablaPasaje();
    }

    //arma la tabla Pasaje
    private void armarCabeceraTablaPasaje() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Tipo");
        filaCabecera.add("Importe");

        for (Object it : filaCabecera) {
            modeloPasaje.addColumn(it);
        }
        jTPasaje.setModel(modeloPasaje);
    }

    private void borrarTablaPasaje() {
        int indice = modeloPasaje.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modeloPasaje.removeRow(i);
        }
    }

    //Arma la Tabla Alojamiento
    private void armarCabeceraTablaAlojamiento() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Tipo");
        filaCabecera.add("Importe");

        for (Object it : filaCabecera) {
            modeloAlojamiento.addColumn(it);
        }
        jTAlojamiento.setModel(modeloAlojamiento);
    }

    private void borrarTablaAlojamiento() {
        int indice = modeloAlojamiento.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modeloAlojamiento.removeRow(i);
        }
    }

    private void borrarContenidoFormulario() {
        borrarTablaAlojamiento();
        borrarTablaPasaje();
        jTNombreOrigen.setText("");
        jtNombreDestino.setText("");
        jDInicio.setCalendar(null);
        jDSalida.setCalendar(null);
        jTTemporada.setText("");
        jTCantDias.setText("");
        jTImporteTotal.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTNombreOrigen = new javax.swing.JTextField();
        jtNombreDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlojamiento = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPasaje = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDInicio = new com.toedter.calendar.JDateChooser();
        jDSalida = new com.toedter.calendar.JDateChooser();
        jTImporteTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTCantDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSCantPersonas = new javax.swing.JSpinner();
        jTTemporada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTCliente = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de paquetes");

        jTNombreOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreOrigenActionPerformed(evt);
            }
        });

        jtNombreDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreDestinoActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese ciudad de origen : ");

        jLabel3.setText("Ingrese ciudad de destino :");

        jTAlojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Importe Diario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTAlojamiento);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Alojamientos Disponibles");

        jButton5.setText("Buscar Pasajes y Alojamientos Disponibles");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Pasajes Disponibles");

        jTPasaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTPasaje);

        jLabel8.setText("Fecha Inicio:");

        jLabel9.setText("Fecha Salida:");

        jTImporteTotal.setEnabled(false);

        jLabel11.setText("Total de Días:");

        jTCantDias.setEnabled(false);

        jLabel4.setText("Cantidad de Personas:");

        jSCantPersonas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSCantPersonas.setValue(1);

        jTTemporada.setEnabled(false);

        jLabel5.setText("Temporada:");

        jButton4.setText("Calcular Importe Total y Confirmar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Importe Total");

        jLabel12.setText("Nombre del Cliente: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTNombreOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11)))
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtNombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTCantDias, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3))))))
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(288, 288, 288)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jButton5)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombreOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtNombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jSCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jDSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCantDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jButton2)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreOrigenActionPerformed

    private void jtNombreDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreDestinoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Busca la ciudad de Origen y Completa la Tabla Pasajes con lo Disponible
        // TODO add your handling code here:
        borrarTablaAlojamiento();
        borrarTablaPasaje();
        Ciudad ciudadOrigen = new Ciudad();
        Ciudad ciudadDestino = new Ciudad();
        CiudadData city = new CiudadData();
        Pasaje pasajeEncontrado = new Pasaje();
        PasajeData pass = new PasajeData();
        Alojamiento alojamientiEncontrado = new Alojamiento();
        AlojamientoData aloj = new AlojamientoData();

        ciudadOrigen = city.buscarCiudad(jTNombreOrigen.getText());
        ciudadDestino = city.buscarCiudad(jtNombreDestino.getText());

        if (ciudadOrigen != null && ciudadDestino != null) {

            List<Pasaje> pasajes = pass.listarPasajesOrigenDestino(ciudadOrigen.getIdCiudad(), ciudadDestino.getIdCiudad());

            for (Pasaje p : pasajes) {
                modeloPasaje.addRow(new Object[]{p.getIdPasaje(), p.getTipoTransporte(), p.getImporte()});
            }

            List<Alojamiento> alojamientos = aloj.listarAlojamientosIDciudad(ciudadDestino.getIdCiudad());

            for (Alojamiento a : alojamientos) {
                modeloAlojamiento.addRow(new Object[]{a.getIdAlojamiento(), a.getNombre(), a.getTipoAlojamiento(),a.getImporteDiario()});
            }

        } else {
            JOptionPane.showMessageDialog(null, "No hay un Pasaje Disponible con esa combinacion de Origen y Destino ");
            borrarContenidoFormulario();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double importeAlojamiento;
        double importePasaje;

        if (jDInicio.getDate() == null || jDSalida.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Debe Completar Ambos Campos de Fecha Inicio/Salida");
            return;
        }
        // Calcula el Importe Total del Paquete

        //calcular si es temporada alta, media, o baja
        LocalDate fechaI = jDInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        DateTimeFormatter dti = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        //jLfecha.setText("Fecha: "+fechaN.format(dtf));
        LocalDate fechaF = jDSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        if (fechaI.isAfter(fechaF)) {
            JOptionPane.showMessageDialog(null, "La Fecha de Inicio no puede ser posterior a la de Salida :-)");
            return;
        } else {
            //calcula los dias de alojamiento
            if (fechaI.getMonthValue() == 1 || fechaI.getMonthValue() == 7) {
                jTTemporada.setText("Alta");
            } else if (fechaI.getMonthValue() == 2 || fechaI.getMonthValue() == 6) {
                jTTemporada.setText("Media");
            } else {
                jTTemporada.setText("Baja");
            }

            long totaldias = ChronoUnit.DAYS.between(fechaI, fechaF);
            jTCantDias.setText(totaldias + "");
        }

        if (jTAlojamiento.getSelectedRow() != -1 && jTPasaje.getSelectedRow() != -1) {
            importeAlojamiento = (Double) modeloAlojamiento.getValueAt(jTAlojamiento.getSelectedRow(), 3);
            importePasaje = (Double) modeloPasaje.getValueAt(jTPasaje.getSelectedRow(), 2);
            //calculo usando los días y cantidad de Personas en Temporada Baja:
            double importeTotalBaja = ((importeAlojamiento * Double.valueOf(jTCantDias.getText())) * (Integer) jSCantPersonas.getValue() + (importePasaje * (Integer) jSCantPersonas.getValue()));
            //se Agrega o no el porcentaje que correspondería si es Temporada Alta:
            double importeTotalAlta = importeTotalBaja * 1.3;
            //se Agrega o no el porcentaje que correspondería si es Temporada Media:
            double importeTotalMedia = importeTotalBaja * 1.15;
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Pasaje y Alojamiento");
            return;
        }

        //calculo usando los días y cantidad de Personas en Temporada Baja:
        double importeTotalBaja = ((importeAlojamiento * Double.valueOf(jTCantDias.getText())) * (Integer) jSCantPersonas.getValue() + (importePasaje * (Integer) jSCantPersonas.getValue()));
        //se Agrega o no el porcentaje que correspondería si es Temporada Alta:
        double importeTotalAlta = importeTotalBaja * 1.3;
        //se Agrega o no el porcentaje que correspondería si es Temporada Media:
        double importeTotalMedia = importeTotalBaja * 1.15;

        if (jTTemporada.getText().equals("Alta")) {
            jTImporteTotal.setText(importeTotalAlta + "");
        } else if (jTTemporada.getText().equals("Media")) {
            jTImporteTotal.setText(importeTotalMedia + "");
        } else {
            jTImporteTotal.setText(importeTotalBaja + "");
        }

        //muestra el cuadro de Dialogo de la Confirmación del Paquete
        JFrame frame = new JFrame("Confirmar Creación de Paquete");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        //primero pasamos las fechas al formato que queremos usar:
        String diaInicio = Integer.toString(jDInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesInicio = Integer.toString(jDInicio.getCalendar().get(Calendar.MONTH)+1);
        String añoInicio = Integer.toString(jDInicio.getCalendar().get(Calendar.YEAR));
        String fechaInicio = diaInicio+"/"+mesInicio+"/"+añoInicio;
        String diaSalida = Integer.toString(jDSalida.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesSalida = Integer.toString(jDSalida.getCalendar().get(Calendar.MONTH)+1);
        String añoSalida = Integer.toString(jDSalida.getCalendar().get(Calendar.YEAR));
        String fechaSalida = diaSalida+"/"+mesSalida+"/"+añoSalida;
        
        
        int respuesta = JOptionPane.showConfirmDialog(frame, "El Importe Total del Pasaje es $: "+jTImporteTotal.getText()+
                "\nOrigen: "+jTNombreOrigen.getText()+
                "\nDestino: "+jtNombreDestino.getText()+
                "\nCantidad de Personas: "+jSCantPersonas.getValue()+
                "\nCantidad de Días: "+jTCantDias.getText()+
                "\nTemporada: "+jTTemporada.getText()+
                "\nTransporte: "+modeloPasaje.getValueAt(jTPasaje.getSelectedRow(), 1)+
                "\nAlojamiento: "+modeloAlojamiento.getValueAt(jTAlojamiento.getSelectedRow(),1)+
                "\nFecha Salida: "+fechaInicio+
                "\nFecha Regreso: "+fechaSalida, "Confirmar la Creación del Paquete Turístico", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            // Hizo click en cofirmar asi que se va a guardar el Paquete
            
            Ciudad ciudadOrigen = new Ciudad();
            Ciudad ciudadDestino = new Ciudad();
            CiudadData city = new CiudadData();
            Pasaje pasajeEncontrado = new Pasaje();
            PasajeData pass = new PasajeData();
            Alojamiento alojamientoEncontrado = new Alojamiento();
            AlojamientoData aloj = new AlojamientoData();
            Paquete nuevoPaquete = new Paquete();
            PaqueteData pack = new PaqueteData();

            //busca la ciudad de Origen y la de Destino y las asigna
            ciudadOrigen = city.buscarCiudad(jTNombreOrigen.getText());
            ciudadDestino = city.buscarCiudad(jtNombreDestino.getText());
            //busca el Alojamiento y lo asigna
            alojamientoEncontrado = aloj.buscarAlojamiento((Integer) modeloAlojamiento.getValueAt(jTAlojamiento.getSelectedRow(), 0));
            //busca el Pasaje y lo asigna
            pasajeEncontrado = pass.buscarPasaje((Integer) modeloPasaje.getValueAt(jTPasaje.getSelectedRow(), 0));

            nuevoPaquete.setOrigen(ciudadOrigen);
            nuevoPaquete.setDestino(ciudadDestino);
            nuevoPaquete.setAlojamiento(alojamientoEncontrado);
            nuevoPaquete.setPasaje(pasajeEncontrado);
            nuevoPaquete.setEstado(true);
            nuevoPaquete.setCliente(jTCliente.getText());
            nuevoPaquete.setCantPersonas((Integer)jSCantPersonas.getValue());
            nuevoPaquete.setImporte(Double.parseDouble(jTImporteTotal.getText()));
            nuevoPaquete.setTemporada(jTTemporada.getText());
            nuevoPaquete.setCantDias(Integer.valueOf(jTCantDias.getText()));

            //manejo de la fecha para agregar al paquete
            LocalDate fechaSalidas = jDInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaLlegada = jDSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            dti = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            nuevoPaquete.setFechaSalida(fechaSalidas);
            nuevoPaquete.setFechaLLegada(fechaLlegada);

            //llama al método para guardar el paquete
            pack.guardarPaquete(nuevoPaquete);

            borrarContenidoFormulario();
        }else {
            //Hizo click en no así que no se va a guardar el paquete y vuelve para ver si quiere modificarlo
            return;
        }

        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        borrarContenidoFormulario();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDInicio;
    private com.toedter.calendar.JDateChooser jDSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSCantPersonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTAlojamiento;
    private javax.swing.JTextField jTCantDias;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTImporteTotal;
    private javax.swing.JTextField jTNombreOrigen;
    private javax.swing.JTable jTPasaje;
    private javax.swing.JTextField jTTemporada;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jtNombreDestino;
    // End of variables declaration//GEN-END:variables
}
